### ISSUE TITLE
Output of "None" when decrypting password

### ISSUE THREAD

**Issue by Joeboyc2** [HurricaneLabs/splunksecrets#4]
Running the follow command:
`splunksecrets --splunk-secret-text dCqLei7Z1083bZoMCZpU782Qh3Y8elemrNAEb/ba9QzvXWdJeJcx40KZ55hVLjq9sH30r7v4t7as6KD4IBeCeG1TYuVvRmxh7PPzzwJKLpSXuBKObK/3Y5LXJrQH9SAaDNpfDzTT2TO4XWXCnqcrGM0ct5qLtnyJYKrcB0YbOcMa1M1aoecuy.80qgWpz/EDcLqUT.GM1BC6Kbz1vbX8pjHvrX8G7Tcf5lKFKOC.sOBAC9gXEPnRFCz0xf.GoW -D --password $1$ec3vkicywd+IN1M=`

I just get this as an output:
`None`

I cant find any documentation that would suggest what this means or if i have done something wrong

**Comment by mcm** [comment]
Try escaping the dollar signs on the command line. They’re probably being interpreted by your shell as variables.

**Comment by Joeboyc2** [comment]
--password `\$1\$ec3vkicywd+IN1M=`
Gives me:

`Traceback (most recent call last):
  File "/usr/local/lib64/python3.6/site-packages/cryptography/utils.py", line 36, in _check_byteslike
    memoryview(value)
TypeError: memoryview: a bytes-like object is required, not 'str'`

`During handling of the above exception, another exception occurred:`

`Traceback (most recent call last):
  File "/usr/local/bin/splunksecrets", line 11, in <module>
    load_entry_point('splunksecrets==0.4.0', 'console_scripts', 'splunksecrets')()
  File "/usr/local/lib/python3.6/site-packages/splunksecrets.py", line 137, in main
    output = decrypt(key, ciphertext, args.nosalt)
  File "/usr/local/lib/python3.6/site-packages/splunksecrets.py", line 25, in decrypt
    algorithm = algorithms.ARC4(key)
  File "/usr/local/lib64/python3.6/site-packages/cryptography/hazmat/primitives/ciphers/algorithms.py", line 112, in __init__
    self.key = _verify_key_size(self, key)
  File "/usr/local/lib64/python3.6/site-packages/cryptography/hazmat/primitives/ciphers/algorithms.py", line 16, in _verify_key_size
    utils._check_byteslike("key", key)
  File "/usr/local/lib64/python3.6/site-packages/cryptography/utils.py", line 38, in _check_byteslike
    raise TypeError("{} must be bytes-like".format(name))
TypeError: key must be bytes-like`

&
--password `/$1/$ec3vkicywd+IN1M=`
Gives me `None`

**Comment by mcm** [comment]
Running it like this just worked for me. You need to use `\$` rather than `/$`
```
~ ❯❯❯ splunksecrets --splunk-secret-text dCqLei7Z1083bZoMCZpU782Qh3Y8elemrNAEb/ba9QzvXWdJeJcx40KZ55hVLjq9sH30r7v4t7as6KD4IBeCeG1TYuVvRmxh7PPzzwJKLpSXuBKObK/3Y5LXJrQH9SAaDNpfDzTT2TO4XWXCnqcrGM0ct5qLtnyJYKrcB0YbOcMa1M1aoecuy.80qgWpz/EDcLqUT.GM1BC6Kbz1vbX8pjHvrX8G7Tcf5lKFKOC.sOBAC9gXEPnRFCz0xf.GoW -D --password \$1\$ec3vkicywd+IN1M=
--- your password here ---
~ ❯❯❯
```

**Comment by Joeboyc2** [comment]
i'm having absolutely no luck with this :(
I have tried in both linux and windows, but i still get the none output
any chance you can just send me the output.... i have a copy of the password i think it should be but i just need to confirm before generating new certs

**Comment by mcm** [comment]
I can do that, but I’m definitely interested in trying to figure out why it’s not working for you. Not sure what time zone you’re in, but would you be able to do a screenshare at some point to look at it? Alternatively can you send a screenshot of the terminal window when you try to run it?

**Comment by Joeboyc2** [comment]
In in the UK, its 18:48 here, in the GMT time Zone
Happy to do a screen share when your free
I've tried at home now, with little difference in results, i have used a pi with raspbian, and my windows 10 laptop

Running your exact line above, with a fresh install of the pip app, running on windows10 python 3.6.5 i get this:
![image](https://user-images.githubusercontent.com/8202030/64366626-84582700-d00e-11e9-8725-66d89ce1ae21.png)

**Comment by mcm** [comment]
Can you actually try saving the splunk secret text to a file, and running like this? I think I found the bug, and this will confirm for sure.

```
~ ❯❯❯ splunksecrets --splunk-secret <filename> -D
Encrypted password: $1$ec3vkicywd+IN1M=
(redacted)
~ ❯❯❯
```

If you want to pass the password on the command line, the $ should _only_ be escaped on Mac/Linux, and not on Windows. That's also mixing us up here a bit. Letting the tool prompt for it will avoid that for us.

Let me know if this works, and if so I'll publish a fixed version and then have you update and retest.

**Comment by Joeboyc2** [comment]
Humm, interesting development
I now get an output :), but its nothing like i expected it to be.....
The one you get, does it start `(.` if it does i will try it on the machine i am having trouble decrypting the cert on

**Comment by mcm** [comment]
Yes, that's the password I get.

**Comment by mcm** [comment]
Would you be open to sending me (in a secure channel) what you were expecting so that I can play around with a few things?

**Comment by Joeboyc2** [comment]
OK so the password was odd because i hadn't added the --nosalt option (as it is a sslpassword) it then came out starting `lk`, this as still not what i expected it to be (i was given a password it should have been, by someone else)
Anyhow, I've tried the password that was generated and it is working fine.

I'm absolutely chuffed! its taken up far too much of my time today and im so pleased its now working

Thank you for all your help with this @mcm

**Comment by mcm** [comment]
OK awesome! I'll get the minor bug we found patched. Thanks for the report.

**Comment by Joeboyc2** [comment]
Great stuff, glad I could help out little bit
